### ISSUE TITLE
--server-version flag doesn't seem to take effect for edgedb project init

### ISSUE THREAD

**Issue by naartjie** [edgedb/edgedb-cli#1012]
- EdgeDB Version:
2.14+bc002ae

- EdgeDB CLI Version:
EdgeDB CLI 2.3.1+5d93f42

- OS Version:
macOS 13.2.1

Steps to Reproduce:

Run project init on an existing project. Expected to get 2.12 server version, but got latest 2.14 installed instead:

```
❯ edgedb project init --server-version '2.12'
Found `edgedb.toml` in /Users/naartjie/Projects/Phosphor/orgs/server
Initializing project...
Specify the name of EdgeDB instance to use with this project [default: server]:
> orgZ
Checking EdgeDB versions...
┌────────────────────────┬───────────────────────────────────────────────────────────┐
│ Project directory      │ /Users/naartjie/Projects/Phosphor/orgs/server             │
│ Project config         │ /Users/naartjie/Projects/Phosphor/orgs/server/edgedb.toml │
│ Schema dir (non-empty) │ /Users/naartjie/Projects/Phosphor/orgs/server/dbschema    │
│ Installation method    │ portable package                                          │
│ Version                │ 2.14+bc002ae                                              │
│ Instance name          │ orgZ                                                      │
└────────────────────────┴───────────────────────────────────────────────────────────┘
Version 2.14+bc002ae is already installed
```

**Comment by tailhook** [comment]
It takes effect. The `2.12` means `>= 2.12 and < 3` (i.e. the most recent version that is compatible with 2.12).

We discussed this a lot and this seems to be the best way to treat versions.

To set specific minor version use `--server-version '=2.12'`.

Leaving this open, as we should print a message about that I think, to make it more understandable, though.

**Comment by naartjie** [comment]
Okay, and thank you for the quick response.

It seems pretty unintuitive (coming from other tools). If I really wanted latest `< 3` I'd expect to have to use `< 3` in `--server-version`. But I'm just saying from a new user getting the least of a surprise point of view, I understand your decision for it to mean whatever you want it to mean.

**Comment by tailhook** [comment]
> It seems pretty unintuitive (coming from other tools).

To add to the picture: this is the version that is written in `edgedb.toml`. When you maintain that file you want to set minimum supported version in case you need some bugfix for that project. But you also don't want your other team members to install the next major version, and commit app that uses features of that new major version (because other team members and production don't have them yet).

This is not without precedent. `Cargo.toml`'s default version treatment is also like this.

That said, in command-line it's a bit more weird than in the toml file. But we don't want to have different treatment of versions in `toml` and command-line.
