### ISSUE TITLE
Add migration support to EdgeDB library

### ISSUE THREAD

**Issue by XAMPPRocky** [edgedb/edgedb-cli#1046]
Hello 👋 We're interested in being able to programmatically migrate our EdgeDB instance, however currently the migrate command is only supported in the CLI, and there's currently no `lib.rs` in the project, which means the functionality couldn't be pulled in as a library. It would be nice if this functionality could be exposed here or in `edgedb-tokio`.

**Comment by tailhook** [comment]
It's doable with (on latest bindings and on EdgeDB server 3.0-rc.1):
```rust
use tokio::fs;


#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = edgedb_tokio::create_client().await?;
    let mut dir = fs::read_dir("./dbschema/migrations").await?;
    let mut paths = Vec::new();
    while let Some(entry) = dir.next_entry().await? {
        paths.push(entry.path());
    }
    paths.sort();
    for path in paths {
        let edgeql = fs::read_to_string(path).await?;
        match cli.query::<String, _>(&edgeql, &()).await {
            Ok(_) => {}
            Err(e) if e.is::<edgedb_errors::DuplicateMigrationError>() => {
                continue;
            }
            Err(e) if e.is::<edgedb_errors::NoResultExpected>() => {
                continue;
            }
            Err(e) => return Err(e)?,
        }
    }
    Ok(())
}
```

We still have not decided what is the strategy to provide it to language bindings, mostly because it should not run on every instance of the app because that will impact startup time quite a lot (and possibly performance of other connections on restart).

[execute](edgedb/edgedb-rust#241) will improve the code above a bit.

**Comment by XAMPPRocky** [comment]
Thank you for the response! 

> We still have not decided what is the strategy to provide it to language bindings, mostly because it should not run on every instance of the app because that will impact startup time quite a lot (and possibly performance of other connections on restart).

This part I'm a bit confused by, I'm not looking to perform it on every instance on startup, I'm building a project that at certain times wants to migrate and upgrade the EdgeDB schema based on user inputs. So I'd only ever be migrating at specific times that I've manually specified in my app.

**Comment by XAMPPRocky** [comment]
Also we tested the above code snippet out and this doesn't appear to address the original issue.

The code above is for applying generated `.edgeql` migrations, where as what we want to do is apply using the `.esdl` schema.

**Comment by tailhook** [comment]
> 
> The code above is for applying generated `.edgeql` migrations, where as what we want to do is apply using the `.esdl` schema.

Oh. We don't have an intention to implement that in bindings. Since the process is quite complex.

But technically CLI tools is just one client. So if you have very specific needs and want to invest some time into doing that, there is nothing that prevents you from the implementation. Start with looking at [migrations RFC](https://github.com/edgedb/rfcs/blob/master/text/1000-migrations.rst) and [START MIGRATION TO docs](https://www.edgedb.com/docs/reference/ddl/migrations#start-migration).

> This part I'm a bit confused by, I'm not looking to perform it on every instance on startup, I'm building a project that at certain times wants to migrate and upgrade the EdgeDB schema based on user inputs. So I'd only ever be migrating at specific times that I've manually specified in my app.

Note, that without any precautions users can easily send concurrent queries. This will not break EdgeDB itself, but might require some programmatic handing of conflicts.

**Comment by XAMPPRocky** [comment]
> Oh. We don't have an intention to implement that in bindings. Since the process is quite complex.

I mean you've already implemented it in Rust in the CLI, what I'm asking for is the exact same functionality in the library. If the CLI is "just one client", then I don't see the motivation for it being only in the CLI, as programmatic migration and initialisation are common in SQL integrations, and in a world where this is trying to be a replacement for SQL, it seems like the client bindings should be on-par with the functionality of the CLI. Forking and maintaining potentially divergent migration logic is not a good downstream user experience, and I'd rather not have to install the `edgedb-cli` on every distribution of the app to achieve that functionality.

> This will not break EdgeDB itself, but might require some programmatic handing of conflicts.

This is to me is further motivation that it should be available in the library rather than just the CLI, shelling out to the CLI makes error handling harder for users, and if edgedb's goal is "delivering the best developer experience in databases", providing idiomatic error handling should be a goal.

**Comment by tailhook** [comment]
> I mean you've already implemented it in Rust in the CLI, what I'm asking for is the exact same functionality in the library. If the CLI is "just one client", then I don't see the motivation for it being only in the CLI,

It's complex, and interactive. The API for that will be big and will break on every occasion. Also it's hard to document what has to be provided on every piece of input required, like: "here we have a fill expression of the open-ended number of kinds, you have to provide something here", and then if your expression is wrong it can be rolled back, etc.

And then if we implement that API it's not clear that it will add much value on top of raw queries.

We're still working on various migration features and those imaginary APIs will grow. So it's not just providing a method `client.create_migration("filename.edgeql")`.

Also we're trying to commit to a single set of capabilities for all client bindings. Implementing migration creation in all languages is huge undertaking. And a source for breaking changes on every release.

Our design doesn't need too much knowledge on the client side, so eventually we may provide those APIs in bindings. But not at our current team size. Since editing the schema programmatically is not our primary use case for now.

**Comment by tailhook** [comment]
Also if you're doing things programmatically it might make sense to use DDL directly, instead of composing SDL and then using migrations. (I mean you can issue a `DDL` command per user action like create field and remove field).

**Comment by XAMPPRocky** [comment]
Let me expand a bit more on our use-case more, as there seems to be a large miscommunication between in what I'm trying to ask for, and what you think I'm asking for. For example; I have no interest and would never want an interactive migration API from an EdgeDB library.

We're building an server app that uses EdgeDB as its backing storage, and we want to allow people to be able to self host the app locally for demos, local development, or their own personal use. As such when the program is initialising, we want to check if our module has been installed/applied to the edgedb database, and if not we want to apply the ESDL that is embedded with the program to the database so that the program can then use EdgeDB.

**Comment by tailhook** [comment]
Oh, it should not be hard. Something along the lines of:

```
use tokio::fs;

// Until we implement `Transaction::execute`
async fn execute(tx: &mut edgedb_tokio::Transaction, text: &str) -> anyhow::Result<() {
      match tx.query::<String, _>(&edgeql, &()).await {
          Ok(_) => Ok(()),
          Err(e) if e.is::<edgedb_errors::NoResultExpected>() => {
              Ok(())
          }
          Err(e) => return Err(e)?,
      }
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = edgedb_tokio::create_client().await?;
    cli.transaction(|tx| {
      let mut dir = fs::read_dir("./dbschema/").await?;
      let mut esdl = String::from("START MIGRATION TO {\n");
      while let Some(entry) = dir.next_entry().await? {
          esdl += fs::read_to_string(entry.path()).await?;
      }
      esdl.push_str("}");
      execute(cli, &esdl).await?;
      execute(cli, "POPULATE MIGRATION").await?;
      execute(cli, "COMMIT MIGRATION").await?;
      Ok(())
   }).await?;
   Ok(())
}
```
