### ISSUE TITLE
Implement edgedb server deinit

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#151]
We need a counterpart to `edgedb server init` to remove an instance.

**Comment by tailhook** [comment]
Let's bikeshed on a name a little bit. I'm including `init` command name also, in case we want to change that:
1. `init`/`deinit` -- sounds like it's hard to find `deinit`
2. `init`/`destroy`
3. `init`/`remove` or `init`/`delete` -- sounds like bad pairs of commands
4. `create-instance`/`delete-instance` -- looks like too long (some installations may not have CLI completion)
5. `new-instance`/`delete-instance` -- not much shorter
5. `init`/`remove-instance` -- might be good, removing should not be taken lightly

My favorite at the moment is (2) `init`/`destroy`. It's reasonably short. Reasonably good couple. And `destroy` is a good name for a non-reversible operation.

**Comment by 1st1** [comment]
IMO `new` and `destroy` play nicer together than `init` and `destroy`. @msullivan curious what you think.

**Comment by msullivan** [comment]
I like `init`/`destroy` - they have something of a history of being used together, (pthread_mutex_init/pthread_mutex_destroy and friends, for example).

I maybe like `create`/`destroy` more?

**Comment by tailhook** [comment]
Reopening until we settle up on the name.

`new` is not a verb, so probably worse.

`create`/`destroy` sounds fine. Perhaps `init` was previously chosen because that was meant to initialize default database rather than to create an instance.

On the other hand, that should probably be `create`/`drop` like we have in the language.

And saying that I think it's still tempting to choose a different keyword:
1. `init`/`destroy` for instances
2. `create`/`drop` for DDL
3. `insert`/`delete` for data

**Comment by tailhook** [comment]
This issue added `destroy` command. While it provides context, it's not directly about renaming `init`. So for anyone feeling strongly about renaming `init` should open a new issue. Also see [`project-init`](https://github.com/edgedb/edgedb/discussions/1789) so `init` would rarely be used (except maybe in tutorials) which going to be used instead in many cases.
