### ISSUE TITLE
Allow to switch between different string rendering in REPL

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb-cli#2]
There should be a command in REPL that allows switching between different string rendering (escaped vs. "as is") so that we don't lock the user into one mode for everything. 

In my mind this seems analogous to `\x` in psql. Perhaps we might use that command.

**Comment by tailhook** [comment]
Since we already support multi-argument commands, we have five options:
1. `\set strings compact` /  `\set strings expanded`
2. `\set expand-strings on` /  `\set expand-strings off`
3. `\expand-strings` /  `\no-expand-strings` (there are precedents like `\implicit-properties`)
4. `\strings compact` / `\strings expanded` (we have `\output json` /  `\output tab-separated`)
5. `\expand-strings` / `\compact-strings` (we have `\vi` /  `\emacs`)

I'm proponent of (4). It's both: compact enough and extensible. We already document them under `Settings` section, so no need to prefix with `\set`. And it's unlikely we have 100 settings to make that confusing.

Wording `strings`, `expanded`, `compact`, `on`, `off` is open to bike-shedding too.

**Comment by elprans** [comment]
I think we shouldn't mix *commands* (i.e. `\connect`, `\describe`) and frontend settings in the same namespace.  IMO, using `\set` consistently for rendering preferences would be ideal, also from discoverability perspective `\set <tab> ... completions`.

**Comment by 1st1** [comment]
+1 to what @elprans said (i was saying pretty much the same before).

> \set expand-strings on / \set expand-strings off

I like this one the best.

**Comment by tailhook** [comment]
> I think we shouldn't mix _commands_ (i.e. `\connect`, `\describe`) and frontend settings in the same namespace. IMO, using `\set` consistently for rendering preferences would be ideal, also from discoverability perspective `\set <tab> ... completions`.

Should we also move all of this?
```
Settings
  \limit [LIMIT]           Set implicit LIMIT. Defaults to 100, specify 0 to disable.
  \output [MODE]           Set output mode. One of:
                             json, json-elements, default, tab-separated
  \vi                      switch to vi-mode editing
  \emacs                   switch to emacs (normal) mode editing, disables vi-mode
  \implicit-properties     print implicit properties of objects (id, type id)
  \no-implicit-properties  disable printing implicit properties
  \introspect-types        print typenames instead of `Object` (may fail if
                           schema is updated after enabling option)
  \no-introspect-types     disable type introspection
  \verbose-errors          print all errors with maximum verbosity
  \no-verbose-errors       only print InternalServerError with maximum verbosity
```

**Comment by elprans** [comment]
> Should we also move all of this?

Yes.

`\vi` and `\emacs` becomes `\set input-mode vi|emacs`

The boolean toggles become just that: `\set implicit-properties on|off` etc.
