### ISSUE TITLE
Implement command to synchronize migrations in the filesystem with database

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#270]
See edgedb/edgedb#2356 for context.

**Comment by raddevon** [comment]
I'm guessing we'll add some sort of command to do this. If a user is trying to work with migrations in the CLI when their files are missing, would it make sense to proactively ask them if they want to sync files from the database?

Maybe they run `edgedb migration create` to create a migration with some new schema changes. Rather than giving them `edgedb error: There is no database revision m1gu3lwz67iosj6snahhoyw2tv34hfu5f2vkvwojnboxa5ls5nmstq in the filesystem. Consider updating sources.`, could we instead say something like `Migration files are missing. Would you like to create them from migrations in the database? y/n` or something to that effect? Maybe this also makes sense in the case of `edgedb migrate`?
