### ISSUE TITLE
\psql should use our postgres/bin, not the system one

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#32]
```
yury> \psql
Error executing command: Error running "psql" "-h" "/Users/yury/.edgedb" "-U" "edgedb" "-p" "55043" "-d" "edgedb"
```

^ I don't have system postgres, so there's no `psql` command in my `$PATH`.

Our Python repl code does this to locate the `psql` we built as part of our vendored postgres:

```
        pg_config = buildmeta.get_pg_config_path()
        psql = pg_config.parent / 'psql'
```

Please find a way to replicate this functionality.

**Comment by tailhook** [comment]
Python does that because it is in the same package as edgedb itself. When we use current CLI tools we can use them against *multiple different* edgedb servers, including ones not installed locally.

So to replicate that, we need to expose postgres directory from the edgedb server itself. And that still doesn't work if you have edgedb in a docker container or remotely. 

So I expect this to be postponed until we have `edgedb setup` which may be able to find distributions on the current machine (I'm still not sure it's easy to figure out which distribution to use in that case too).

**Comment by elprans** [comment]
`\psql` is a development feature, so it always implies the local EdgeDB build.  Whether the server is remote or not doesn't matter as long as it exposes the underlying Postgres connection parameters.

**Comment by tailhook** [comment]
> `\psql` is a development feature, so it always implies the local EdgeDB build. Whether the server is remote or not doesn't matter as long as it exposes the underlying Postgres connection parameters.

Connection parameters yes. But we're discussing the path of the `psql` binary.

**Comment by elprans** [comment]
> But we're discussing the path of the `psql` binary.

Again, this is a devmode feature. We assume that both the `edgedb-cli` *and* the EdgeDB build are produced by the same `setup.py` run.  In this sense, there's absolutely no difference between the Rust CLI and the Python CLI.

**Comment by 1st1** [comment]
And `\psql` shouldn't even be visible in `\h` or otherwise available if its a non-dev build of edgedb.

**Comment by tailhook** [comment]
So I'm going to do following:
1. Expose some env variable during `cargo install`
2. Check that as the first directory for `psql` tool, falling back to `PATH`

**Comment by 1st1** [comment]
I'm not sure what you mean by (1), but (2) makes sense. I'll wait for a PR!

**Comment by 1st1** [comment]
Some

**Comment by tailhook** [comment]
I've improved error reporting, so try again. Also make sure that this an instance installed by edgedb not your manually built binary.

**Comment by 1st1** [comment]
> Also make sure that this an instance installed by edgedb not your manually built binary.

Ah, that was the case actually. Sorry for the noise.
