### ISSUE TITLE
support binary protocol version 0.11

### ISSUE THREAD

**Issue by fmoor** [edgedb/edgedb-cli#362]
The [object type descritpor](https://www.edgedb.com/docs/internals/protocol/typedesc#object-shape-descriptor) shape element flags field is increasing in size from 8 to 32 bits with binary protocol version 0.11. This change should be made in the cli before the server changes are merged because the server test suite depends on the cli for dump/restore tests. The cli should remain backwards compatible with older protocol versions.

### References
- [server changes](https://github.com/edgedb/edgedb/pull/2603)
- [edgedb-python changes](https://github.com/edgedb/edgedb-python/pull/195/checks?check_run_id=2861909352#step:8:382)

**Comment by fmoor** [comment]
@tailhook do you have availability to work on this?

**Comment by tailhook** [comment]
Sure. Can do at monday

**Comment by tailhook** [comment]
I also have to update two other things: protocol 0.10 and relative delta.

But [this error](https://github.com/edgedb/edgedb/pull/2603/checks?check_run_id=2861538875#step:16:385) is not because CLI don't support new version of protocol. Because this crashes on a dump version (which is not the same as protocol version, at least conceptually), and also generated by the server itself on restore. CLI looks like fine with both dumping and restoring those.

**Comment by tailhook** [comment]
Fixed in #369
