### ISSUE TITLE
`edgedb project upgrade --to-nightly` doesn't seem to work

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#395]
I've a pre-existing project running with an old-ish nighly.  Running `edgedb project upgrade --to-nightly` on it doesn't seem to do anything and gives me this:

```
$ edgedb project upgrade --to-nightly
Setting `server-version = "nightly"` in `edgedb.toml`
Instance upgraded to 202107090222221cb44c
Remember to commit it to the version control.
```

A newer `nightly` is actually available, although not the latest.

```
$ edgedb server list-versions
┌───────────────┬────────────────────────────────────────────────┬───────────┬───────────┬────────────────────┐
│ Major Version │                  Full Version                  │ Available │ Installed │       Param        │
...
│ nightly       │ nightly_1-beta3-dev202107231400_cv202107231400 │ docker    │           │ --nightly          │
└───────────────┴────────────────────────────────────────────────┴───────────┴───────────┴────────────────────┘
```

**Comment by fantix** [comment]
Oh that was because `202107090222221cb44c` (your current version, deprecated tag) was greater than `1-beta3-dev202107231400_cv202107231400` (the latest version, new tag format), and the `InstanceUpgrade` (operation of `--to-nightly`) will bail out early with an INFO log saying "Version is up to date, skipping".

However, there are still 3 issues I found reading the code and learning from @tailhook:

1. The message is misleading. It says:

    ```
    Setting `server-version = "nightly"` in `edgedb.toml`
    Instance upgraded to 202107090222221cb44c
    Remember to commit it to the version control.
    ```
    
    For the first line, you should already have `nightly` in your `edgedb.toml`.  But let's say it is okay because `--to-nightly` indicates that the CLI will anyway update the `edgedb.toml` with `server-version = "nightly"`, however the reminder in the third line is definitely confusing because the file is not changed and there is nothing to commit.
    
    The second line is also confusing because there is no upgrade done. It would be helpful to see the INFO log but that is by default hidden.

2. According to @tailhook, you should use `edgedb project upgrade` without the `--to-nightly` for minor version upgrades, and `--to-nightly` is not supposed to trigger a minor version upgrade. But with the latest Docker hub I could successfully upgrade my local instance from an old nightly (with new-style tag) to the latest nightly with the `--to-nightly` flag. Reading the source code, `InstanceUpgrade` (operation of `--to-nightly`) won't upgrade minor versions for non-nightly instances, but it will do so for nightlys.

3. Running `edgedb project upgrade` without `--to-nightly` will upgrade the minor version of all instances, instead of only the instance used by the current project. I will be able to verify this tomorrow with a new nightly, but by far the code reads like that. Also, the message from this command is confusing, when all my instances are up to date:

    ```
    Major version matches. Running a minor version upgrade.
    ```
    
    Even with `RUST_LOG=debug` and `--verbose`, I don't know if a minor version upgrade is executed or not, or on which instance, or versions/reasons about the decision.

I will draft a few PRs to address the 3 issues above, but the issue [mentioned at the beginning](https://github.com/edgedb/edgedb-cli/issues/395#issue-954169672) is not an issue (I'll likely add a warning message to make it clear, depending on our decision of issue 2).

**Comment by elprans** [comment]
> and `--to-nightly` is not supposed to trigger a minor version upgrade

This seems rather arbitrary.  `--to-nightly` should get me the latest nightly regardless of whether it'll be "minor" or "major".

**Comment by tailhook** [comment]
This should be fixed by #403

**Comment by tailhook** [comment]
> This seems rather arbitrary. --to-nightly should get me the latest nightly regardless of whether it'll be "minor" or "major".

Well, I would expect it to be no-op if any nightly is currently running. Although, In current implementation (after #403) it does the upgrade, so...

**Comment by tailhook** [comment]
Oh, yes this is an artifact from times when there was only one nightly :(

**Comment by tailhook** [comment]
Should be fixed for portable builds (only).
