### ISSUE TITLE
`instance_ports.json` still has old instance and port data, even after deleting the instance

### ISSUE THREAD

**Issue by clmno** [edgedb/edgedb-cli#474]
- EdgeDB Version: beta-3
- EdgeDB CLI Version: beta-3
- OS Version: Ubuntu

Steps to Reproduce:

1. Delete an instance
```
edgedb instance destroy edgedb_quickstart
```
2. View the latest `instance_ports.json` file
```
cat ~/.config/edgedb/instance_ports.json
```

```
{
  "test": 10700,
  "edgedb_quickstart": 10701
}
```

**Comment by tailhook** [comment]
Yes. This is intentional. So you can destroy and recreate and instance and not be confused. If we don't keep these names, dropping an instance then later creating one could change the port or occupy port of another instance recently dropped. So for example if you have a browser tab opened for the instance and you refresh it you could be confused of seeing very different database. 

While some of that confusion is solved by changing password (so existing clients will not connect to the new database), I don't think there will be shortage of ports somewhere or that json file could be that huge to create problems.
