### ISSUE TITLE
Make `edgedb restore` silent

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-cli#55]
Currently it outputs a bunch of stats:

```
Schema applied in 18.016791906s
Blocks sent in 5.529895ms
Complete in 18.045443671s
OK: RESTORE
```

**Comment by tailhook** [comment]
I've made `--verbose` flag for that. But by default printing nothing is problematic because of two things:
1. For most users it's hard to differentiate between normal and error return, shell is often unhelpful in this case (we print something on our own errors, but others also happen). Especially this is important on bad `#!/bin/sh` scripts. So some "okay" message should be by default in my opinion.
2. There is a special `Waiting for complete` message that prints something if restore command hangs. On large inputs in may work for minutes or even hours. It's very useful to know if the problem on this side or the database side.

So I would rather increase default verbosity by adding a progressbar.

**Comment by 1st1** [comment]
> But by default printing nothing (which is already in master) is problematic because of two things:

I agree. It would be cool to have a progress bar. If we decide to output some progress information we also need a `--quiet` flag to disable it.
