### ISSUE TITLE
[systemctl] Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined

### ISSUE THREAD

**Issue by embium** [edgedb/edgedb-cli#596]
- EdgeDB Version: 1.0-dev.6244+ff49205
- OS Version: Linux vultr 5.10.0-9-amd64 edgedb/edgedb#1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

Steps to Reproduce:

1. Run the command `edgedb instance start perfect_stack`

`[systemctl] Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
edgedb error: service start failed: exit status: 1 (command-line: "systemctl" "--user" "start" "edgedb-server@perfect_stack.service")`

**Comment by tailhook** [comment]
You can run `edgedb instance start --foreground perfect_stack`.

Other than that there is very little we can do if `systemd --user` is not running. I'm not even sure it's viable to improve error message here, because there are so many ways systemd client can fail.

On the other hand, we will likely be working on systemd-less runner soon, we'll see what we can do.

**Comment by embium** [comment]
> You can run edgedb instance start --foreground perfect_stack.

Thanks, that's what I've done.

> Other than that there is very little we can do if systemd --user is not running. I'm not even sure it's viable to improve error message here, because there are so many ways systemd client can fail.

I wasn't sure what the error was exactly indicating but you've summed it up for me.

> On the other hand, we will likely be working on systemd-less runner soon, we'll see what we can do.

That's good news.
