### ISSUE TITLE
Change the "case-sensitive mode" option from "I" to "C" in REPL

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb-cli#6]
Using `I` to mean "case-sensitive" is counter-intuitive because the "I" seems to typically mean "case-**I**nsensitive". So the suggestion is to change this option to `C` so that the mnemonic hint is that it is "**C**ase-sensitive" mode.

**Comment by 1st1** [comment]
@edgedb/all we need to make a decision on this one.

**Comment by RobertoPrevato** [comment]
I read this thread a few days ago, but didn't write a comment to take some time to think.
My considerations:
* I agree with @vpetrovykh that "I" suggets _case insensitive_: it's the same for regular expressions, and my mind goes there. However I wouldn't think anything _bad_ about software that uses "I" as a parameter for `case-sensitive`. Maybe I would be surprised the first couple of times, but I wouldn't mind.
* A single capital "I" can be annoying  because it can be confused with a lowercase "L"
* I don't like `--case-sensitive` because too verbose, `-c` and `--case` because they don't tell which kind of case (sensitive or insensitive?)
* Database collations use `_cs` for case sensitive and `_ci` for case insensitive: to me it feels as natural as the "i" regex modifier for **insensitive**

Since we are in the context of a DB and our users are likely to have knowledge of SQL, is to take example from database collations and use the same abbreviations:
```-ci / -cs```

**Comment by elprans** [comment]
I like consistency with the command line syntax and the use of command-line style flags.  Regarding the flag naming and semantics, let's consider flipping the default to case-sensitive and use `-i` to enable case-insensitive matching.

**Comment by tailhook** [comment]
@RobertoPrevato 
> Since we are in the context of a DB and our users are likely to have knowledge of SQL, my vote goes for taking example from database collations and use the same abbreviations:
> `-ci / -cs`

Modern command-line thinks that: `-ci` is a pair of two independent parameters that can be used separately or as `-ic`. We can make `--ci` shortcut though.

@elprans 
> Regarding the flag naming and semantics, let's consider flipping the default to case-sensitive and use `-i` to enable case-insensitive matching.

I agree with @1st1 that insensitive is what most users will want. We can treat `-I` as reverse `-i`, though (we just need to rename `S` to `-s` to be consistent with that, which we can do with command-line semantics).

**Comment by tailhook** [comment]
Anyway, it looks like everybody agrees with command-line semantics: https://github.com/edgedb/edgedb-cli/issues/31

It's kinda fine with keeping `-I` as reverse of "case insensitive" here, except it is unabbreviated as `--case-sensitive`, making `I` a bit unclear. Some options are:
* Change long name `-I=--no-insensitive` (bug that long argument looks not great)
* Add a no-op `-i, --case-insensitive` argument to show symmetry
* Or keep as is.

**Comment by 1st1** [comment]
> It's kinda fine with keeping -I as reverse of "case insensitive" here, except it is unabbreviated as --case-sensitive, making I a bit unclear. Some options are:

yes

> Add a no-op -i, --case-insensitive argument to show symmetry

+1, but I wouldn't add `--case-insensitive` or similar long command options -- IMO extended options are needed when you have LOTS of options; when it's just 2-3 of them, using `-x` short options is fine.
