### ISSUE TITLE
CLI does not work well inside Emacs Shell

### ISSUE THREAD

**Issue by rajrahul** [edgedb/edgedb-cli#666]
- EdgeDB Version: EdgeDB CLI 1.0.0+5724c50
- OS Version: Ubuntu

Steps to Reproduce:
CLI inside emacs-shell reads a trailing newline character when options are input 
```
rahul@pop-os:~/workspace/edgedb/quickstart$ edgedb migration create
did you create object type 'default::Person'? [y,n,l,c,b,s,q,?]
> y
edgedb error: Invalid option "y\n", please use one of: [y,n,l,c,b,s,q,?]
```

**Comment by tailhook** [comment]
Thanks for the report. I think this is because emacs doesn't allocate a tty. Non-tty mode is fixed in #667.

Also note that generally if emacs run programs not in a pseudo-tty, there will be some disabled functionality anyway: no highlighting, completion, etc. I think there should be a better terminal support in emacs.
