### ISSUE TITLE
CLI tries to autostart non existent and remote instances

### ISSUE THREAD

**Issue by Syzuna** [edgedb/edgedb-cli#830]
- EdgeDB Version:  2.1+c73716f
- EdgeDB CLI Version: 2.1.0-dev.840+683a890
- OS Version: Windows 11, Version 21H2

Steps to Reproduce:

1.  I am not sure how this happened so I am also not sure how to reproduce the remote instance autostart as it only does it for 1 of mine.
2. typo the name of an instance

The CLI tries to autostart remote instances and instances that dont exist (not locally and not remote).
I typoed the name of an instance once and since then it tries to autostart it.

![KQgg89laEH](https://user-images.githubusercontent.com/22714301/187045241-1c073ef8-bd08-429d-89e2-e73a5c6c7527.png)

**Comment by tailhook** [comment]
As far as I understand it's because someone tried to run `edgedb instance start` for that instance at some point. This is fixed in #836 (should be in nightly tomorrow). You will be able to run `edgedb instance stop <name>` (ignoring error) to remove startup files using tomorrow nightly, and `start` will error out earlier.

Let me know if you notice the but under other circumstances.

**Comment by Syzuna** [comment]
Looks good now. 
The unwanted autostart tries seem to be gone after doing an `edgedb instance stop -I <name>` for them 👍🏻
