### ISSUE TITLE
Implement `edgedb database wipe`

### ISSUE THREAD

**Issue by elprans** [edgedb/edgedb-cli#839]
Depends on edgedb/edgedb#4351.

**Comment by elprans** [comment]
`RESET SCHEMA TO initial` has landed, so this is unblocked now.

**Comment by buzinas** [comment]
@elprans I tried to use `RESET SCHEMA TO initial` today but it didn't work and then I realized that it's marked as 3.0.

 A few quick questions:
- Do you have any plans to ship this feature on v2? If so, when?
- Otherwise, is there any ETA for v3 release? Is there an alpha or beta version available?

Sorry for asking, but I couldn't find anything on the website. Thanks!

**Comment by buzinas** [comment]
Cool, thanks! For branch previews, this operation is super important, because ideally we'd reset the schema to initial every time a new change is pushed (and then apply all migrations) – so people can just amend their commits etc.

An operation to amend a migration would be even more valuable, and I know it's on the roadmap 😁 

What's the workaround? I tried [your recommendation](https://github.com/edgedb/edgedb-cli/issues/733#issuecomment-1158840040) but it doesn't let me drop the database due to other connections.

I can kill the connections directly in Postgres, but I have no idea how to do it in EdgeDB.

**Comment by tailhook** [comment]
> What's the workaround? I tried https://github.com/edgedb/edgedb-cli/issues/733#issuecomment-1158840040 but it doesn't let me drop the database due to other connections.

Ah, yes in this scenario it's not great, unfortunately.
