### ISSUE TITLE
make `edgedb instance create` region-aware

### ISSUE THREAD

**Issue by zackelan** [edgedb/edgedb-cli#951]
**current behavior**

when I create a cloud instance, the "closest" region is chosen automatically for me. this is currently opaque to the user, there's no indication for them which region was chosen.

this can also result in inconsistent behavior and user surprise - eg I create one instance, then log in to a VPN to do something unrelated like watch Netflix, and then create a 2nd instance. if the VPN changes what my "closest" EdgeDB Cloud region is, the two instances get created in different regions.

**desired behavior**

I should be able to specify `--region antarctica-east-1` or whatever 

I should be able to run `--region help` or a similar command that gives me the "menu" of which regions are available. this may expand over time, so it should be pulled from an API call to the cloud rather than hardcoded within the CLI.

**Comment by tailhook** [comment]
`--region` is fine. I also think that default should be set in cloud UI. So if users do that manually from their laptop, the instance created will be closer to their application rather than to their laptop. I mean they need to be able to switch between "closest" and specific region in the control panel.
